### ISSUE TITLE
feat: Generic Response 구현

### ISSUE THREAD

**Issue by choigy1001** [CheoCharm/MapZ-Server#11]
# 해결 방법
> response 에 대하여 협의 후 구현 

# To-Do
- [ ]  제네릭 Response 메서드 구현

**Comment by kiiiyeon** [comment]
저는 code랑 data 두 개만 주면 좋을 것 같아요
code는 1,2,3 이런거 말고 그냥 404 405 이런걸로 아니면 문자열!
code 404
message 에러 문자열
이렇게 줘도 좋을듯?!
